//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteAhorcado.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClienteAhorcado.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string btnCancelar {
            get {
                return ResourceManager.GetString("btnCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CANCELAR.
        /// </summary>
        public static string btnCancelarMuys {
            get {
                return ResourceManager.GetString("btnCancelarMuys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Sesión.
        /// </summary>
        public static string btnCerrarSesion {
            get {
                return ResourceManager.GetString("btnCerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clasificación.
        /// </summary>
        public static string btnClasificacion {
            get {
                return ResourceManager.GetString("btnClasificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREAR.
        /// </summary>
        public static string btnCrear {
            get {
                return ResourceManager.GetString("btnCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Cuenta.
        /// </summary>
        public static string btnCrearCuenta {
            get {
                return ResourceManager.GetString("btnCrearCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Partida.
        /// </summary>
        public static string btnCrearPartida {
            get {
                return ResourceManager.GetString("btnCrearPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Perfil.
        /// </summary>
        public static string btnEditarPerfil {
            get {
                return ResourceManager.GetString("btnEditarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Cambios.
        /// </summary>
        public static string btnGuardarCambios {
            get {
                return ResourceManager.GetString("btnGuardarCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Partida (Demo).
        /// </summary>
        public static string btnIniciarPartidaDemo {
            get {
                return ResourceManager.GetString("btnIniciarPartidaDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        public static string btnIniciarSesion {
            get {
                return ResourceManager.GetString("btnIniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a JUGAR.
        /// </summary>
        public static string btnJugar {
            get {
                return ResourceManager.GetString("btnJugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi Perfil.
        /// </summary>
        public static string btnMiPerfil {
            get {
                return ResourceManager.GetString("btnMiPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Estadísticas.
        /// </summary>
        public static string btnMisEstadísticas {
            get {
                return ResourceManager.GetString("btnMisEstadísticas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OPCIONES.
        /// </summary>
        public static string btnOpciones {
            get {
                return ResourceManager.GetString("btnOpciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones.
        /// </summary>
        public static string btnOpcionesMi {
            get {
                return ResourceManager.GetString("btnOpcionesMi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar Cuenta.
        /// </summary>
        public static string btnRegistrar {
            get {
                return ResourceManager.GetString("btnRegistrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SALIR.
        /// </summary>
        public static string btnSalir {
            get {
                return ResourceManager.GetString("btnSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UNIRSE.
        /// </summary>
        public static string btnUnirse {
            get {
                return ResourceManager.GetString("btnUnirse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a Partida.
        /// </summary>
        public static string btnUnirsePartida {
            get {
                return ResourceManager.GetString("btnUnirsePartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrincante.
        /// </summary>
        public static string columContrincante {
            get {
                return ResourceManager.GetString("columContrincante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Usuario.
        /// </summary>
        public static string columCorreo {
            get {
                return ResourceManager.GetString("columCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string columFecha {
            get {
                return ResourceManager.GetString("columFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Partida.
        /// </summary>
        public static string columNombrePartida {
            get {
                return ResourceManager.GetString("columNombrePartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Usuario.
        /// </summary>
        public static string columNombreUsuario {
            get {
                return ResourceManager.GetString("columNombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Palabra.
        /// </summary>
        public static string columPalabra {
            get {
                return ResourceManager.GetString("columPalabra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntos.
        /// </summary>
        public static string columPuntos {
            get {
                return ResourceManager.GetString("columPuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultado.
        /// </summary>
        public static string columResultado {
            get {
                return ResourceManager.GetString("columResultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abandonaste la partida. Se aplicará penalización..
        /// </summary>
        public static string msgAbandonoPropio {
            get {
                return ResourceManager.GetString("msgAbandonoPropio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El adivinador huyó por miedo. ¡Tú ganas!.
        /// </summary>
        public static string msgAbandonoRivalAdiv {
            get {
                return ResourceManager.GetString("msgAbandonoRivalAdiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El juez abandonó la partida. ¡Tú ganas!.
        /// </summary>
        public static string msgAbandonoRivalJuez {
            get {
                return ResourceManager.GetString("msgAbandonoRivalJuez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agotaste tus intentos. Has sido ahorcado..
        /// </summary>
        public static string msgAdivinadorDerrota {
            get {
                return ResourceManager.GetString("msgAdivinadorDerrota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Felicidades! Adivinaste la palabra..
        /// </summary>
        public static string msgAdivinadorVictoria {
            get {
                return ResourceManager.GetString("msgAdivinadorVictoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambios guardados con éxito..
        /// </summary>
        public static string MsgCambiosGuardados {
            get {
                return ResourceManager.GetString("MsgCambiosGuardados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, llena todos los campos y selecciona una palabra para la partida..
        /// </summary>
        public static string msgCamposPartidaIncompletos {
            get {
                return ResourceManager.GetString("msgCamposPartidaIncompletos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes dejar campos vacíos..
        /// </summary>
        public static string MsgCamposVacios {
            get {
                return ResourceManager.GetString("MsgCamposVacios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conectado a la partida &apos;{0}&apos;..
        /// </summary>
        public static string msgConectadoPartida {
            get {
                return ResourceManager.GetString("msgConectadoPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro que deseas abandonar la partida? Perderás puntos de clasificación..
        /// </summary>
        public static string msgConfirmarAbandono {
            get {
                return ResourceManager.GetString("msgConfirmarAbandono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Deseas cancelar la creación de la partida?.
        /// </summary>
        public static string msgConfirmarCancelarPartida {
            get {
                return ResourceManager.GetString("msgConfirmarCancelarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La nueva contraseña debe tener al menos 8 caracteres..
        /// </summary>
        public static string MsgContraseniaCorta {
            get {
                return ResourceManager.GetString("MsgContraseniaCorta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener al menos 8 caracteres por seguridad..
        /// </summary>
        public static string msgContraseniaSeguridad {
            get {
                return ResourceManager.GetString("msgContraseniaSeguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, ingresa un correo electrónico válido (ejemplo: usuario@correo.com)..
        /// </summary>
        public static string msgCorreoInvalido {
            get {
                return ResourceManager.GetString("msgCorreoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico ya está registrado. Si ya tienes cuenta, intenta iniciar sesión..
        /// </summary>
        public static string msgCorreoRegistrado {
            get {
                return ResourceManager.GetString("msgCorreoRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró el usuario o la contraseña es incorrecta..
        /// </summary>
        public static string msgCredencialesIncorrectas {
            get {
                return ResourceManager.GetString("msgCredencialesIncorrectas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos enviados no son válidos para el servidor..
        /// </summary>
        public static string MsgDatosInvalidos {
            get {
                return ResourceManager.GetString("MsgDatosInvalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos enviados no cumplen con los requisitos del servidor..
        /// </summary>
        public static string msgDatosInvalidosServidor {
            get {
                return ResourceManager.GetString("msgDatosInvalidosServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error interno en el servidor de base de datos. Intenta más tarde..
        /// </summary>
        public static string msgErrorBD {
            get {
                return ResourceManager.GetString("msgErrorBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error en la base de datos al intentar crear la partida..
        /// </summary>
        public static string msgErrorBDCrearPartida {
            get {
                return ResourceManager.GetString("msgErrorBDCrearPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al abrir el canal de espera: {0}.
        /// </summary>
        public static string msgErrorCanalEspera {
            get {
                return ResourceManager.GetString("msgErrorCanalEspera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar categorías: {0}.
        /// </summary>
        public static string msgErrorCargarCategorias {
            get {
                return ResourceManager.GetString("msgErrorCargarCategorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar palabras: {0}.
        /// </summary>
        public static string msgErrorCargarPalabras {
            get {
                return ResourceManager.GetString("msgErrorCargarPalabras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar la lista de partidas: {0}.
        /// </summary>
        public static string msgErrorCargarPartidas {
            get {
                return ResourceManager.GetString("msgErrorCargarPartidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de comunicación con el servidor, intente más tarde..
        /// </summary>
        public static string msgErrorComunicacion {
            get {
                return ResourceManager.GetString("msgErrorComunicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al comunicar con el servidor: {0}.
        /// </summary>
        public static string msgErrorComunicarServidor {
            get {
                return ResourceManager.GetString("msgErrorComunicarServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al conectar con el servidor: {0}.
        /// </summary>
        public static string msgErrorConectarServidor {
            get {
                return ResourceManager.GetString("msgErrorConectarServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al intentar comunicar con el servidor: {0}.
        /// </summary>
        public static string MsgErrorConexion {
            get {
                return ResourceManager.GetString("MsgErrorConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al conectar con el servidor: {0} 
        ///Se usarán los datos locales de sesión..
        /// </summary>
        public static string msgErrorConexionRespaldo {
            get {
                return ResourceManager.GetString("msgErrorConexionRespaldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al enviar la letra: {0}.
        /// </summary>
        public static string msgErrorEnviarLetra {
            get {
                return ResourceManager.GetString("msgErrorEnviarLetra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al enviar veredicto: {0}.
        /// </summary>
        public static string msgErrorEnviarVeredicto {
            get {
                return ResourceManager.GetString("msgErrorEnviarVeredicto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error inesperado en el servidor..
        /// </summary>
        public static string msgErrorInesperadoServidor {
            get {
                return ResourceManager.GetString("msgErrorInesperadoServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor detectó un error en tu evaluación.\n\nLa letra &apos;{0}&apos; NO forma parte de la palabra.\n\nPor favor, emite el veredicto correcto..
        /// </summary>
        public static string msgErrorJuicioNo {
            get {
                return ResourceManager.GetString("msgErrorJuicioNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor detectó un error en tu evaluación.\n\nLa letra &apos;{0}&apos; SÍ forma parte de la palabra.\n\nPor favor, emite el veredicto correcto..
        /// </summary>
        public static string msgErrorJuicioSi {
            get {
                return ResourceManager.GetString("msgErrorJuicioSi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudieron recuperar los datos del perfil desde el servidor..
        /// </summary>
        public static string msgErrorRecuperarPerfil {
            get {
                return ResourceManager.GetString("msgErrorRecuperarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error interno del servidor. Intenta de nuevo más tarde..
        /// </summary>
        public static string MsgErrorServidor {
            get {
                return ResourceManager.GetString("MsgErrorServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al intentar unirse a la partida: {0}.
        /// </summary>
        public static string msgErrorUnirsePartida {
            get {
                return ResourceManager.GetString("msgErrorUnirsePartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, selecciona una fecha de nacimiento válida..
        /// </summary>
        public static string msgFechaInvalida {
            get {
                return ResourceManager.GetString("msgFechaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, ingresa tu usuario y contraseña..
        /// </summary>
        public static string msgIngresarCredenciales {
            get {
                return ResourceManager.GetString("msgIngresarCredenciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El adivinador descubrió la palabra. ¡Derrota!.
        /// </summary>
        public static string msgJuezDerrota {
            get {
                return ResourceManager.GetString("msgJuezDerrota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El adivinador no lo logró. ¡Victoria!.
        /// </summary>
        public static string msgJuezVictoria {
            get {
                return ResourceManager.GetString("msgJuezVictoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡El jugador {0} se ha unido a la partida!
        ///El juego va a comenzar..
        /// </summary>
        public static string msgJugadorUnido {
            get {
                return ResourceManager.GetString("msgJugadorUnido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has marcado la letra como {0}.
        /// </summary>
        public static string msgJuicioLetra {
            get {
                return ResourceManager.GetString("msgJuicioLetra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, llena todos los campos para continuar..
        /// </summary>
        public static string msgLlenarCampos {
            get {
                return ResourceManager.GetString("msgLlenarCampos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de la partida ya está en uso. Por favor, elige otro..
        /// </summary>
        public static string msgNombrePartidaEnUso {
            get {
                return ResourceManager.GetString("msgNombrePartidaEnUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Partida &apos;{0}&apos; creada con éxito!.
        /// </summary>
        public static string msgPartidaCreadaExito {
            get {
                return ResourceManager.GetString("msgPartidaCreadaExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo unir a la partida. Es posible que ya no esté disponible..
        /// </summary>
        public static string msgPartidaNoDisponible {
            get {
                return ResourceManager.GetString("msgPartidaNoDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrando cuenta....
        /// </summary>
        public static string msgRegistrandoCuenta {
            get {
                return ResourceManager.GetString("msgRegistrandoCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Cuenta registrada con éxito!.
        /// </summary>
        public static string msgRegistroExitoso {
            get {
                return ResourceManager.GetString("msgRegistroExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor devolvió una respuesta desconocida..
        /// </summary>
        public static string msgRespuestaDesconocida {
            get {
                return ResourceManager.GetString("msgRespuestaDesconocida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, selecciona una partida de la lista para unirte..
        /// </summary>
        public static string msgSeleccionarPartida {
            get {
                return ResourceManager.GetString("msgSeleccionarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya hay una sesión activa para este usuario..
        /// </summary>
        public static string msgSesionActiva {
            get {
                return ResourceManager.GetString("msgSesionActiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo conectar con el servidor, intente más tarde..
        /// </summary>
        public static string msgSinConexion {
            get {
                return ResourceManager.GetString("msgSinConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró una sesión activa. Volviendo al inicio..
        /// </summary>
        public static string msgSinSesionActiva {
            get {
                return ResourceManager.GetString("msgSinSesionActiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, ingresa un número de teléfono válido....
        /// </summary>
        public static string MsgTelefonoInvalido {
            get {
                return ResourceManager.GetString("MsgTelefonoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor tardó demasiado en responder..
        /// </summary>
        public static string msgTiempoAgotado {
            get {
                return ResourceManager.GetString("msgTiempoAgotado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario ya está en uso. Por favor, elige otro..
        /// </summary>
        public static string msgUsuarioEnUso {
            get {
                return ResourceManager.GetString("msgUsuarioEnUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró tu usuario en la base de datos..
        /// </summary>
        public static string MsgUsuarioNoEncontrado {
            get {
                return ResourceManager.GetString("MsgUsuarioNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario ya está ocupado..
        /// </summary>
        public static string MsgUsuarioOcupado {
            get {
                return ResourceManager.GetString("MsgUsuarioOcupado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACTUALIZAR.
        /// </summary>
        public static string textActualizar {
            get {
                return ResourceManager.GetString("textActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar por:.
        /// </summary>
        public static string textBuscarpor {
            get {
                return ResourceManager.GetString("textBuscarpor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría: {0}.
        /// </summary>
        public static string textCategoria {
            get {
                return ResourceManager.GetString("textCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración Partida.
        /// </summary>
        public static string textConfiguraciónPartida {
            get {
                return ResourceManager.GetString("textConfiguraciónPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        public static string textContraseña {
            get {
                return ResourceManager.GetString("textContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correcto.
        /// </summary>
        public static string textCorrecto {
            get {
                return ResourceManager.GetString("textCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico:.
        /// </summary>
        public static string textCorreo {
            get {
                return ResourceManager.GetString("textCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Derrotas:.
        /// </summary>
        public static string textDerrotas {
            get {
                return ResourceManager.GetString("textDerrotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espera mientras se conecta un contrincante....
        /// </summary>
        public static string textEsperaContrincante {
            get {
                return ResourceManager.GetString("textEsperaContrincante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Nacimiento:.
        /// </summary>
        public static string textFechaNacimiento {
            get {
                return ResourceManager.GetString("textFechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial de Partidas.
        /// </summary>
        public static string textHistorialPartidas {
            get {
                return ResourceManager.GetString("textHistorialPartidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string textIdioma {
            get {
                return ResourceManager.GetString("textIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrecto.
        /// </summary>
        public static string textIncorrecto {
            get {
                return ResourceManager.GetString("textIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio Sesión.
        /// </summary>
        public static string textInicioSesion {
            get {
                return ResourceManager.GetString("textInicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Letra Elegida:.
        /// </summary>
        public static string textLetraElegida {
            get {
                return ResourceManager.GetString("textLetraElegida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de la partida:.
        /// </summary>
        public static string textNombrePartida {
            get {
                return ResourceManager.GetString("textNombrePartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre(s):.
        /// </summary>
        public static string textNombres {
            get {
                return ResourceManager.GetString("textNombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de Usuario:.
        /// </summary>
        public static string textNombreUsuario {
            get {
                return ResourceManager.GetString("textNombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Contraseña:.
        /// </summary>
        public static string textNuevaContraseña {
            get {
                return ResourceManager.GetString("textNuevaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partidas jugadas:.
        /// </summary>
        public static string textPartidasjugadas {
            get {
                return ResourceManager.GetString("textPartidasjugadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pista.
        /// </summary>
        public static string textPista {
            get {
                return ResourceManager.GetString("textPista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primer Apellido:.
        /// </summary>
        public static string textPrimerApellido {
            get {
                return ResourceManager.GetString("textPrimerApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntaje Global.
        /// </summary>
        public static string textPuntajeGlobal {
            get {
                return ResourceManager.GetString("textPuntajeGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        public static string textRegistro {
            get {
                return ResourceManager.GetString("textRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Segundo Apellido:.
        /// </summary>
        public static string textSegundoApellido {
            get {
                return ResourceManager.GetString("textSegundoApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Categoría:.
        /// </summary>
        public static string textSeleccionarCategoría {
            get {
                return ResourceManager.GetString("textSeleccionarCategoría", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Palabra.
        /// </summary>
        public static string textSeleccionarPalabra {
            get {
                return ResourceManager.GetString("textSeleccionarPalabra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione una Fecha.
        /// </summary>
        public static string textSeleccioneUnaFecha {
            get {
                return ResourceManager.GetString("textSeleccioneUnaFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono: .
        /// </summary>
        public static string textTelefono {
            get {
                return ResourceManager.GetString("textTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Victorias:.
        /// </summary>
        public static string textVictorias {
            get {
                return ResourceManager.GetString("textVictorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 
        ///Yo: {0}.
        /// </summary>
        public static string textYoChat {
            get {
                return ResourceManager.GetString("textYoChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abandonar.
        /// </summary>
        public static string titAbandonar {
            get {
                return ResourceManager.GetString("titAbandonar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aviso.
        /// </summary>
        public static string titAviso {
            get {
                return ResourceManager.GetString("titAviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campos vacíos.
        /// </summary>
        public static string titCamposVacios {
            get {
                return ResourceManager.GetString("titCamposVacios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar Partida.
        /// </summary>
        public static string titCancelarPartida {
            get {
                return ResourceManager.GetString("titCancelarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conflicto.
        /// </summary>
        public static string titConflicto {
            get {
                return ResourceManager.GetString("titConflicto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña débil.
        /// </summary>
        public static string titContraseniaDebil {
            get {
                return ResourceManager.GetString("titContraseniaDebil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrincante encontrado.
        /// </summary>
        public static string titContrincanteEncontrado {
            get {
                return ResourceManager.GetString("titContrincanteEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Existente.
        /// </summary>
        public static string titCorreoExistente {
            get {
                return ResourceManager.GetString("titCorreoExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo inválido.
        /// </summary>
        public static string titCorreoInvalido {
            get {
                return ResourceManager.GetString("titCorreoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credenciales inválidas.
        /// </summary>
        public static string titCredencialesInvalidas {
            get {
                return ResourceManager.GetString("titCredencialesInvalidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos incompletos.
        /// </summary>
        public static string TitDatosIncompletos {
            get {
                return ResourceManager.GetString("TitDatosIncompletos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desconexión.
        /// </summary>
        public static string titDesconexion {
            get {
                return ResourceManager.GetString("titDesconexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string titError {
            get {
                return ResourceManager.GetString("titError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de conexión.
        /// </summary>
        public static string titErrorConexion {
            get {
                return ResourceManager.GetString("titErrorConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error del Servidor.
        /// </summary>
        public static string titErrorServidor {
            get {
                return ResourceManager.GetString("titErrorServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de Sesión.
        /// </summary>
        public static string titErrorSesion {
            get {
                return ResourceManager.GetString("titErrorSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de Validación.
        /// </summary>
        public static string titErrorValidacion {
            get {
                return ResourceManager.GetString("titErrorValidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Éxito.
        /// </summary>
        public static string titExito {
            get {
                return ResourceManager.GetString("titExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo de comunicación.
        /// </summary>
        public static string titFalloComunicacion {
            get {
                return ResourceManager.GetString("titFalloComunicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo de conexión.
        /// </summary>
        public static string titFalloConexion {
            get {
                return ResourceManager.GetString("titFalloConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha inválida.
        /// </summary>
        public static string titFechaInvalida {
            get {
                return ResourceManager.GetString("titFechaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juicio.
        /// </summary>
        public static string titJuicio {
            get {
                return ResourceManager.GetString("titJuicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre ocupado.
        /// </summary>
        public static string titNombreOcupado {
            get {
                return ResourceManager.GetString("titNombreOcupado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida Finalizada.
        /// </summary>
        public static string titPartidaFinalizada {
            get {
                return ResourceManager.GetString("titPartidaFinalizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida no disponible.
        /// </summary>
        public static string titPartidaNoDisponible {
            get {
                return ResourceManager.GetString("titPartidaNoDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        public static string titRegistro {
            get {
                return ResourceManager.GetString("titRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro Exitoso.
        /// </summary>
        public static string titRegistroExitoso {
            get {
                return ResourceManager.GetString("titRegistroExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sesión Activa.
        /// </summary>
        public static string titSesionActiva {
            get {
                return ResourceManager.GetString("titSesionActiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin conexión.
        /// </summary>
        public static string titSinConexion {
            get {
                return ResourceManager.GetString("titSinConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono inválido.
        /// </summary>
        public static string titTelefonoInvalido {
            get {
                return ResourceManager.GetString("titTelefonoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo agotado.
        /// </summary>
        public static string titTiempoAgotado {
            get {
                return ResourceManager.GetString("titTiempoAgotado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario Existente.
        /// </summary>
        public static string titUsuarioExistente {
            get {
                return ResourceManager.GetString("titUsuarioExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Veredicto Denegado.
        /// </summary>
        public static string titVeredictoDenegado {
            get {
                return ResourceManager.GetString("titVeredictoDenegado", resourceCulture);
            }
        }
    }
}
