//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteAhorcado.PalabraServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PalabraDTO", Namespace="http://schemas.datacontract.org/2004/07/ServidorAhorcado.DTO")]
    [System.SerializableAttribute()]
    public partial class PalabraDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int categoriaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPalabraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string palabraENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string palabraESField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int categoriaId {
            get {
                return this.categoriaIdField;
            }
            set {
                if ((this.categoriaIdField.Equals(value) != true)) {
                    this.categoriaIdField = value;
                    this.RaisePropertyChanged("categoriaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcionEN {
            get {
                return this.descripcionENField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionENField, value) != true)) {
                    this.descripcionENField = value;
                    this.RaisePropertyChanged("descripcionEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcionES {
            get {
                return this.descripcionESField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionESField, value) != true)) {
                    this.descripcionESField = value;
                    this.RaisePropertyChanged("descripcionES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPalabra {
            get {
                return this.idPalabraField;
            }
            set {
                if ((this.idPalabraField.Equals(value) != true)) {
                    this.idPalabraField = value;
                    this.RaisePropertyChanged("idPalabra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string palabraEN {
            get {
                return this.palabraENField;
            }
            set {
                if ((object.ReferenceEquals(this.palabraENField, value) != true)) {
                    this.palabraENField = value;
                    this.RaisePropertyChanged("palabraEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string palabraES {
            get {
                return this.palabraESField;
            }
            set {
                if ((object.ReferenceEquals(this.palabraESField, value) != true)) {
                    this.palabraESField = value;
                    this.RaisePropertyChanged("palabraES");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoriaDTO", Namespace="http://schemas.datacontract.org/2004/07/ServidorAhorcado.DTO")]
    [System.SerializableAttribute()]
    public partial class CategoriaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string categoriaENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string categoriaESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idCategoriaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string categoriaEN {
            get {
                return this.categoriaENField;
            }
            set {
                if ((object.ReferenceEquals(this.categoriaENField, value) != true)) {
                    this.categoriaENField = value;
                    this.RaisePropertyChanged("categoriaEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string categoriaES {
            get {
                return this.categoriaESField;
            }
            set {
                if ((object.ReferenceEquals(this.categoriaESField, value) != true)) {
                    this.categoriaESField = value;
                    this.RaisePropertyChanged("categoriaES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCategoria {
            get {
                return this.idCategoriaField;
            }
            set {
                if ((this.idCategoriaField.Equals(value) != true)) {
                    this.idCategoriaField = value;
                    this.RaisePropertyChanged("idCategoria");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PalabraServiceRef.IPalabraService")]
    public interface IPalabraService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPalabraService/ObtenerPalabrasPorCategoria", ReplyAction="http://tempuri.org/IPalabraService/ObtenerPalabrasPorCategoriaResponse")]
        ClienteAhorcado.PalabraServiceRef.PalabraDTO[] ObtenerPalabrasPorCategoria(int categoriaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPalabraService/ObtenerPalabrasPorCategoria", ReplyAction="http://tempuri.org/IPalabraService/ObtenerPalabrasPorCategoriaResponse")]
        System.Threading.Tasks.Task<ClienteAhorcado.PalabraServiceRef.PalabraDTO[]> ObtenerPalabrasPorCategoriaAsync(int categoriaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPalabraService/ObtenerCategorias", ReplyAction="http://tempuri.org/IPalabraService/ObtenerCategoriasResponse")]
        ClienteAhorcado.PalabraServiceRef.CategoriaDTO[] ObtenerCategorias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPalabraService/ObtenerCategorias", ReplyAction="http://tempuri.org/IPalabraService/ObtenerCategoriasResponse")]
        System.Threading.Tasks.Task<ClienteAhorcado.PalabraServiceRef.CategoriaDTO[]> ObtenerCategoriasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPalabraService/ObtenerDatosPalabra", ReplyAction="http://tempuri.org/IPalabraService/ObtenerDatosPalabraResponse")]
        ClienteAhorcado.PalabraServiceRef.PalabraDTO ObtenerDatosPalabra(int palabraID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPalabraService/ObtenerDatosPalabra", ReplyAction="http://tempuri.org/IPalabraService/ObtenerDatosPalabraResponse")]
        System.Threading.Tasks.Task<ClienteAhorcado.PalabraServiceRef.PalabraDTO> ObtenerDatosPalabraAsync(int palabraID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPalabraServiceChannel : ClienteAhorcado.PalabraServiceRef.IPalabraService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PalabraServiceClient : System.ServiceModel.ClientBase<ClienteAhorcado.PalabraServiceRef.IPalabraService>, ClienteAhorcado.PalabraServiceRef.IPalabraService {
        
        public PalabraServiceClient() {
        }
        
        public PalabraServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PalabraServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PalabraServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PalabraServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClienteAhorcado.PalabraServiceRef.PalabraDTO[] ObtenerPalabrasPorCategoria(int categoriaId) {
            return base.Channel.ObtenerPalabrasPorCategoria(categoriaId);
        }
        
        public System.Threading.Tasks.Task<ClienteAhorcado.PalabraServiceRef.PalabraDTO[]> ObtenerPalabrasPorCategoriaAsync(int categoriaId) {
            return base.Channel.ObtenerPalabrasPorCategoriaAsync(categoriaId);
        }
        
        public ClienteAhorcado.PalabraServiceRef.CategoriaDTO[] ObtenerCategorias() {
            return base.Channel.ObtenerCategorias();
        }
        
        public System.Threading.Tasks.Task<ClienteAhorcado.PalabraServiceRef.CategoriaDTO[]> ObtenerCategoriasAsync() {
            return base.Channel.ObtenerCategoriasAsync();
        }
        
        public ClienteAhorcado.PalabraServiceRef.PalabraDTO ObtenerDatosPalabra(int palabraID) {
            return base.Channel.ObtenerDatosPalabra(palabraID);
        }
        
        public System.Threading.Tasks.Task<ClienteAhorcado.PalabraServiceRef.PalabraDTO> ObtenerDatosPalabraAsync(int palabraID) {
            return base.Channel.ObtenerDatosPalabraAsync(palabraID);
        }
    }
}
