//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteAhorcado.EstadisticasServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadisticasDTO", Namespace="http://schemas.datacontract.org/2004/07/ServidorAhorcado.DTO")]
    [System.SerializableAttribute()]
    public partial class EstadisticasDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int posicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int puntosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int posicion {
            get {
                return this.posicionField;
            }
            set {
                if ((this.posicionField.Equals(value) != true)) {
                    this.posicionField = value;
                    this.RaisePropertyChanged("posicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int puntos {
            get {
                return this.puntosField;
            }
            set {
                if ((this.puntosField.Equals(value) != true)) {
                    this.puntosField = value;
                    this.RaisePropertyChanged("puntos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistorialDTO", Namespace="http://schemas.datacontract.org/2004/07/ServidorAhorcado.DTO")]
    [System.SerializableAttribute()]
    public partial class HistorialDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estadoPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string palabraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int puntosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioContrincanteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estadoPartida {
            get {
                return this.estadoPartidaField;
            }
            set {
                if ((this.estadoPartidaField.Equals(value) != true)) {
                    this.estadoPartidaField = value;
                    this.RaisePropertyChanged("estadoPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaPartida {
            get {
                return this.fechaPartidaField;
            }
            set {
                if ((this.fechaPartidaField.Equals(value) != true)) {
                    this.fechaPartidaField = value;
                    this.RaisePropertyChanged("fechaPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string palabra {
            get {
                return this.palabraField;
            }
            set {
                if ((object.ReferenceEquals(this.palabraField, value) != true)) {
                    this.palabraField = value;
                    this.RaisePropertyChanged("palabra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int puntos {
            get {
                return this.puntosField;
            }
            set {
                if ((this.puntosField.Equals(value) != true)) {
                    this.puntosField = value;
                    this.RaisePropertyChanged("puntos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuarioContrincante {
            get {
                return this.usuarioContrincanteField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioContrincanteField, value) != true)) {
                    this.usuarioContrincanteField = value;
                    this.RaisePropertyChanged("usuarioContrincante");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EstadisticasServiceRef.IEstadisticasService")]
    public interface IEstadisticasService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstadisticasService/ObtenerClasificacionPuntos", ReplyAction="http://tempuri.org/IEstadisticasService/ObtenerClasificacionPuntosResponse")]
        ClienteAhorcado.EstadisticasServiceRef.EstadisticasDTO[] ObtenerClasificacionPuntos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstadisticasService/ObtenerClasificacionPuntos", ReplyAction="http://tempuri.org/IEstadisticasService/ObtenerClasificacionPuntosResponse")]
        System.Threading.Tasks.Task<ClienteAhorcado.EstadisticasServiceRef.EstadisticasDTO[]> ObtenerClasificacionPuntosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstadisticasService/ObtenerClasificacionVictorias", ReplyAction="http://tempuri.org/IEstadisticasService/ObtenerClasificacionVictoriasResponse")]
        ClienteAhorcado.EstadisticasServiceRef.EstadisticasDTO[] ObtenerClasificacionVictorias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstadisticasService/ObtenerClasificacionVictorias", ReplyAction="http://tempuri.org/IEstadisticasService/ObtenerClasificacionVictoriasResponse")]
        System.Threading.Tasks.Task<ClienteAhorcado.EstadisticasServiceRef.EstadisticasDTO[]> ObtenerClasificacionVictoriasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstadisticasService/ObtenerEstadisticaUsuario", ReplyAction="http://tempuri.org/IEstadisticasService/ObtenerEstadisticaUsuarioResponse")]
        ClienteAhorcado.EstadisticasServiceRef.EstadisticasDTO ObtenerEstadisticaUsuario(int idUsuario, int puntosOrVictorias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstadisticasService/ObtenerEstadisticaUsuario", ReplyAction="http://tempuri.org/IEstadisticasService/ObtenerEstadisticaUsuarioResponse")]
        System.Threading.Tasks.Task<ClienteAhorcado.EstadisticasServiceRef.EstadisticasDTO> ObtenerEstadisticaUsuarioAsync(int idUsuario, int puntosOrVictorias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstadisticasService/ObtenerHistorial", ReplyAction="http://tempuri.org/IEstadisticasService/ObtenerHistorialResponse")]
        ClienteAhorcado.EstadisticasServiceRef.HistorialDTO[] ObtenerHistorial(int jugadorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstadisticasService/ObtenerHistorial", ReplyAction="http://tempuri.org/IEstadisticasService/ObtenerHistorialResponse")]
        System.Threading.Tasks.Task<ClienteAhorcado.EstadisticasServiceRef.HistorialDTO[]> ObtenerHistorialAsync(int jugadorID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEstadisticasServiceChannel : ClienteAhorcado.EstadisticasServiceRef.IEstadisticasService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EstadisticasServiceClient : System.ServiceModel.ClientBase<ClienteAhorcado.EstadisticasServiceRef.IEstadisticasService>, ClienteAhorcado.EstadisticasServiceRef.IEstadisticasService {
        
        public EstadisticasServiceClient() {
        }
        
        public EstadisticasServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EstadisticasServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstadisticasServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstadisticasServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClienteAhorcado.EstadisticasServiceRef.EstadisticasDTO[] ObtenerClasificacionPuntos() {
            return base.Channel.ObtenerClasificacionPuntos();
        }
        
        public System.Threading.Tasks.Task<ClienteAhorcado.EstadisticasServiceRef.EstadisticasDTO[]> ObtenerClasificacionPuntosAsync() {
            return base.Channel.ObtenerClasificacionPuntosAsync();
        }
        
        public ClienteAhorcado.EstadisticasServiceRef.EstadisticasDTO[] ObtenerClasificacionVictorias() {
            return base.Channel.ObtenerClasificacionVictorias();
        }
        
        public System.Threading.Tasks.Task<ClienteAhorcado.EstadisticasServiceRef.EstadisticasDTO[]> ObtenerClasificacionVictoriasAsync() {
            return base.Channel.ObtenerClasificacionVictoriasAsync();
        }
        
        public ClienteAhorcado.EstadisticasServiceRef.EstadisticasDTO ObtenerEstadisticaUsuario(int idUsuario, int puntosOrVictorias) {
            return base.Channel.ObtenerEstadisticaUsuario(idUsuario, puntosOrVictorias);
        }
        
        public System.Threading.Tasks.Task<ClienteAhorcado.EstadisticasServiceRef.EstadisticasDTO> ObtenerEstadisticaUsuarioAsync(int idUsuario, int puntosOrVictorias) {
            return base.Channel.ObtenerEstadisticaUsuarioAsync(idUsuario, puntosOrVictorias);
        }
        
        public ClienteAhorcado.EstadisticasServiceRef.HistorialDTO[] ObtenerHistorial(int jugadorID) {
            return base.Channel.ObtenerHistorial(jugadorID);
        }
        
        public System.Threading.Tasks.Task<ClienteAhorcado.EstadisticasServiceRef.HistorialDTO[]> ObtenerHistorialAsync(int jugadorID) {
            return base.Channel.ObtenerHistorialAsync(jugadorID);
        }
    }
}
