//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteAhorcado.PartidaServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartidaLobbyDTO", Namespace="http://schemas.datacontract.org/2004/07/ServidorAhorcado.DTO")]
    [System.SerializableAttribute()]
    public partial class PartidaLobbyDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoJugadorAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombrePartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioJugadorAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correoJugadorA {
            get {
                return this.correoJugadorAField;
            }
            set {
                if ((object.ReferenceEquals(this.correoJugadorAField, value) != true)) {
                    this.correoJugadorAField = value;
                    this.RaisePropertyChanged("correoJugadorA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                if ((this.fechaCreacionField.Equals(value) != true)) {
                    this.fechaCreacionField = value;
                    this.RaisePropertyChanged("fechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPartida {
            get {
                return this.idPartidaField;
            }
            set {
                if ((this.idPartidaField.Equals(value) != true)) {
                    this.idPartidaField = value;
                    this.RaisePropertyChanged("idPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombrePartida {
            get {
                return this.nombrePartidaField;
            }
            set {
                if ((object.ReferenceEquals(this.nombrePartidaField, value) != true)) {
                    this.nombrePartidaField = value;
                    this.RaisePropertyChanged("nombrePartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuarioJugadorA {
            get {
                return this.usuarioJugadorAField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioJugadorAField, value) != true)) {
                    this.usuarioJugadorAField = value;
                    this.RaisePropertyChanged("usuarioJugadorA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartidaDTO", Namespace="http://schemas.datacontract.org/2004/07/ServidorAhorcado.DTO")]
    [System.SerializableAttribute()]
    public partial class PartidaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string categoriaPalabraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionPalabraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estadoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool hayLetraPendienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idIdiomaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idJugadorAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idJugadorBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intentosFallidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char letraPendienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char[] letrasUsadasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombrePartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string palabraObjetivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char[] progresoPalabraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioJugadorAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioJugadorBField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string categoriaPalabra {
            get {
                return this.categoriaPalabraField;
            }
            set {
                if ((object.ReferenceEquals(this.categoriaPalabraField, value) != true)) {
                    this.categoriaPalabraField = value;
                    this.RaisePropertyChanged("categoriaPalabra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcionPalabra {
            get {
                return this.descripcionPalabraField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionPalabraField, value) != true)) {
                    this.descripcionPalabraField = value;
                    this.RaisePropertyChanged("descripcionPalabra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estadoId {
            get {
                return this.estadoIdField;
            }
            set {
                if ((this.estadoIdField.Equals(value) != true)) {
                    this.estadoIdField = value;
                    this.RaisePropertyChanged("estadoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool hayLetraPendiente {
            get {
                return this.hayLetraPendienteField;
            }
            set {
                if ((this.hayLetraPendienteField.Equals(value) != true)) {
                    this.hayLetraPendienteField = value;
                    this.RaisePropertyChanged("hayLetraPendiente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idIdioma {
            get {
                return this.idIdiomaField;
            }
            set {
                if ((this.idIdiomaField.Equals(value) != true)) {
                    this.idIdiomaField = value;
                    this.RaisePropertyChanged("idIdioma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idJugadorA {
            get {
                return this.idJugadorAField;
            }
            set {
                if ((this.idJugadorAField.Equals(value) != true)) {
                    this.idJugadorAField = value;
                    this.RaisePropertyChanged("idJugadorA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idJugadorB {
            get {
                return this.idJugadorBField;
            }
            set {
                if ((this.idJugadorBField.Equals(value) != true)) {
                    this.idJugadorBField = value;
                    this.RaisePropertyChanged("idJugadorB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPartida {
            get {
                return this.idPartidaField;
            }
            set {
                if ((this.idPartidaField.Equals(value) != true)) {
                    this.idPartidaField = value;
                    this.RaisePropertyChanged("idPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intentosFallidos {
            get {
                return this.intentosFallidosField;
            }
            set {
                if ((this.intentosFallidosField.Equals(value) != true)) {
                    this.intentosFallidosField = value;
                    this.RaisePropertyChanged("intentosFallidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char letraPendiente {
            get {
                return this.letraPendienteField;
            }
            set {
                if ((this.letraPendienteField.Equals(value) != true)) {
                    this.letraPendienteField = value;
                    this.RaisePropertyChanged("letraPendiente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char[] letrasUsadas {
            get {
                return this.letrasUsadasField;
            }
            set {
                if ((object.ReferenceEquals(this.letrasUsadasField, value) != true)) {
                    this.letrasUsadasField = value;
                    this.RaisePropertyChanged("letrasUsadas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombrePartida {
            get {
                return this.nombrePartidaField;
            }
            set {
                if ((object.ReferenceEquals(this.nombrePartidaField, value) != true)) {
                    this.nombrePartidaField = value;
                    this.RaisePropertyChanged("nombrePartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string palabraObjetivo {
            get {
                return this.palabraObjetivoField;
            }
            set {
                if ((object.ReferenceEquals(this.palabraObjetivoField, value) != true)) {
                    this.palabraObjetivoField = value;
                    this.RaisePropertyChanged("palabraObjetivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char[] progresoPalabra {
            get {
                return this.progresoPalabraField;
            }
            set {
                if ((object.ReferenceEquals(this.progresoPalabraField, value) != true)) {
                    this.progresoPalabraField = value;
                    this.RaisePropertyChanged("progresoPalabra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuarioJugadorA {
            get {
                return this.usuarioJugadorAField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioJugadorAField, value) != true)) {
                    this.usuarioJugadorAField = value;
                    this.RaisePropertyChanged("usuarioJugadorA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuarioJugadorB {
            get {
                return this.usuarioJugadorBField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioJugadorBField, value) != true)) {
                    this.usuarioJugadorBField = value;
                    this.RaisePropertyChanged("usuarioJugadorB");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PartidaServiceRef.IPartidaService", CallbackContract=typeof(ClienteAhorcado.PartidaServiceRef.IPartidaServiceCallback))]
    public interface IPartidaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaService/CrearPartida", ReplyAction="http://tempuri.org/IPartidaService/CrearPartidaResponse")]
        int CrearPartida(int idJugador, int idPalabra, string nombrePartida, int idIdioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaService/CrearPartida", ReplyAction="http://tempuri.org/IPartidaService/CrearPartidaResponse")]
        System.Threading.Tasks.Task<int> CrearPartidaAsync(int idJugador, int idPalabra, string nombrePartida, int idIdioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaService/ObtenerPartidasDisponibles", ReplyAction="http://tempuri.org/IPartidaService/ObtenerPartidasDisponiblesResponse")]
        ClienteAhorcado.PartidaServiceRef.PartidaLobbyDTO[] ObtenerPartidasDisponibles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaService/ObtenerPartidasDisponibles", ReplyAction="http://tempuri.org/IPartidaService/ObtenerPartidasDisponiblesResponse")]
        System.Threading.Tasks.Task<ClienteAhorcado.PartidaServiceRef.PartidaLobbyDTO[]> ObtenerPartidasDisponiblesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaService/UnirseAPartida", ReplyAction="http://tempuri.org/IPartidaService/UnirseAPartidaResponse")]
        ClienteAhorcado.PartidaServiceRef.PartidaDTO UnirseAPartida(int idPartida, int idJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaService/UnirseAPartida", ReplyAction="http://tempuri.org/IPartidaService/UnirseAPartidaResponse")]
        System.Threading.Tasks.Task<ClienteAhorcado.PartidaServiceRef.PartidaDTO> UnirseAPartidaAsync(int idPartida, int idJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaService/ProponerLetra", ReplyAction="http://tempuri.org/IPartidaService/ProponerLetraResponse")]
        void ProponerLetra(int idPartida, int idJugador, char letra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaService/ProponerLetra", ReplyAction="http://tempuri.org/IPartidaService/ProponerLetraResponse")]
        System.Threading.Tasks.Task ProponerLetraAsync(int idPartida, int idJugador, char letra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaService/JuzgarLetra", ReplyAction="http://tempuri.org/IPartidaService/JuzgarLetraResponse")]
        void JuzgarLetra(int idPartida, int idJugador, bool decisionEsCorrecta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaService/JuzgarLetra", ReplyAction="http://tempuri.org/IPartidaService/JuzgarLetraResponse")]
        System.Threading.Tasks.Task JuzgarLetraAsync(int idPartida, int idJugador, bool decisionEsCorrecta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaService/AbandonarPartida", ReplyAction="http://tempuri.org/IPartidaService/AbandonarPartidaResponse")]
        void AbandonarPartida(int idPartida, int idJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaService/AbandonarPartida", ReplyAction="http://tempuri.org/IPartidaService/AbandonarPartidaResponse")]
        System.Threading.Tasks.Task AbandonarPartidaAsync(int idPartida, int idJugador);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPartidaServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPartidaService/NotificarJugadorUnido")]
        void NotificarJugadorUnido(ClienteAhorcado.PartidaServiceRef.PartidaDTO partida);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPartidaService/NotificarLetraParaJuzgar")]
        void NotificarLetraParaJuzgar(char letra);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPartidaService/NotificarLetraPropuesta")]
        void NotificarLetraPropuesta(char letra, bool esCorrecta, char[] progresoPalabra, int intentosFallidos);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPartidaService/NotificarErrorJuicio")]
        void NotificarErrorJuicio(char letra, bool eraCorrecta);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPartidaService/NotificarFinPartida")]
        void NotificarFinPartida(int estadoFinal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPartidaServiceChannel : ClienteAhorcado.PartidaServiceRef.IPartidaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PartidaServiceClient : System.ServiceModel.DuplexClientBase<ClienteAhorcado.PartidaServiceRef.IPartidaService>, ClienteAhorcado.PartidaServiceRef.IPartidaService {
        
        public PartidaServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public PartidaServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public PartidaServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public PartidaServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public PartidaServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public int CrearPartida(int idJugador, int idPalabra, string nombrePartida, int idIdioma) {
            return base.Channel.CrearPartida(idJugador, idPalabra, nombrePartida, idIdioma);
        }
        
        public System.Threading.Tasks.Task<int> CrearPartidaAsync(int idJugador, int idPalabra, string nombrePartida, int idIdioma) {
            return base.Channel.CrearPartidaAsync(idJugador, idPalabra, nombrePartida, idIdioma);
        }
        
        public ClienteAhorcado.PartidaServiceRef.PartidaLobbyDTO[] ObtenerPartidasDisponibles() {
            return base.Channel.ObtenerPartidasDisponibles();
        }
        
        public System.Threading.Tasks.Task<ClienteAhorcado.PartidaServiceRef.PartidaLobbyDTO[]> ObtenerPartidasDisponiblesAsync() {
            return base.Channel.ObtenerPartidasDisponiblesAsync();
        }
        
        public ClienteAhorcado.PartidaServiceRef.PartidaDTO UnirseAPartida(int idPartida, int idJugador) {
            return base.Channel.UnirseAPartida(idPartida, idJugador);
        }
        
        public System.Threading.Tasks.Task<ClienteAhorcado.PartidaServiceRef.PartidaDTO> UnirseAPartidaAsync(int idPartida, int idJugador) {
            return base.Channel.UnirseAPartidaAsync(idPartida, idJugador);
        }
        
        public void ProponerLetra(int idPartida, int idJugador, char letra) {
            base.Channel.ProponerLetra(idPartida, idJugador, letra);
        }
        
        public System.Threading.Tasks.Task ProponerLetraAsync(int idPartida, int idJugador, char letra) {
            return base.Channel.ProponerLetraAsync(idPartida, idJugador, letra);
        }
        
        public void JuzgarLetra(int idPartida, int idJugador, bool decisionEsCorrecta) {
            base.Channel.JuzgarLetra(idPartida, idJugador, decisionEsCorrecta);
        }
        
        public System.Threading.Tasks.Task JuzgarLetraAsync(int idPartida, int idJugador, bool decisionEsCorrecta) {
            return base.Channel.JuzgarLetraAsync(idPartida, idJugador, decisionEsCorrecta);
        }
        
        public void AbandonarPartida(int idPartida, int idJugador) {
            base.Channel.AbandonarPartida(idPartida, idJugador);
        }
        
        public System.Threading.Tasks.Task AbandonarPartidaAsync(int idPartida, int idJugador) {
            return base.Channel.AbandonarPartidaAsync(idPartida, idJugador);
        }
    }
}
